### ISSUE TITLE
Peak size

### ISSUE THREAD

**Issue by koh2ng0** [ListerLab/pfc_development#10]
Hi,

I have a question about the peak calling and filtering processes of your manuscript. As far as I know, the cis-regulatory elements are approximately range to ~ 500 bp usually. So, some tools (e.g. ArchR) have applied this fact to the peak calling process and comprehensively fixed the size of peaks as 501 bp. However, in your method, the size of peaks and cis-regulatory elements are ranging from 300 bp to 30 kb. Is there any reason that you set such a wider range? Furthermore, when I did, some peaks are over 40 kb. Is it because several peaks are merged into a single peak?

Thanks.

**Comment by herrinca** [comment]
Hi Koh,

@SaskiaFreytag was the one who did the analysis, and you're right that some peaks were merged. That might explain why you're seeing peaks over 40 kb. I think she might be at a conference in the states right now, so she might not be able to get back to you right away. But I'm sure she'll have more details for you when she has a chance.

Chuck

**Comment by SaskiaFreytag** [comment]
Hi Koh,

As explained in the paper we did not use ArchR with fixed peak sizes but instead created our own pipeline. The pipeline is fairly well explained in the manuscript. The large peak sizes are indeed a result of merging and maybe you want to filter peaks according to your own rules.

Cheers,

Saskia

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by koh2ng0** [comment]
Thank you for your kind reply!

sincerely,
Koh
