### ISSUE TITLE
Metadata in Human cell atlas (HCA) portal

### ISSUE THREAD

**Issue by koh2ng0** [ListerLab/pfc_development#11]
Hi,

First of all, thank you for sharing great data. I downloaded and used fastq data via the Human Cell Atlas ([https://data.humancellatlas.org/explore/projects/77dedd59-1376-4887-9bca-dc42b56d5b7a]).
When I checked the metadata uploaded on the HCA, the supplementary table of the paper, and the data information posted on the GEO site, I confirmed that certain content was recorded incorrectly.
Some records in the '**Specimen from organism**' sheet of the metadata do not match with other resources, such as the supplementary data of the paper and GEO. The '**Biomaterial Name**' column and '**Biomaterial ID**' column do not correspond to each other, and there are incorrect entries when matching the '**Biomaterial ID**' with GEO.
I have attached the file that I corrected, and I would appreciate it if you could review it.

[humanCorticalDevelopmentLandscape_metadata_09-12-2022.xlsx](https://github.com/ListerLab/pfc_development/files/11524057/humanCorticalDevelopmentLandscape_metadata_09-12-2022.xlsx)

+) I found something wrong in the manifest file in the HCA portal, too. The sample with SRA number 'SRR13873129' and donor ID 'RL2373' was sequenced by snATAC-seq, but the library is incorrectly written as '10x 3' v3' instead of '10x scATAC-seq' on the manifest. If it is convenient for you, I would greatly appreciate your assistance in verifying the matter.

**Comment by herrinca** [comment]
Thank koh, this has been corrected.
