### ISSUE TITLE
Not matching barcodes

### ISSUE THREAD

**Issue by joonan30** [ListerLab/pfc_development#3]
Dear Charles,

Thanks for the wonderful dataset. It would be very useful resource for the community. 
I have downloaded the dataset from Google Bucket and GEO. So basically, get the barcodes you used for the processed data and match them with raw files.

When I used the `Processed_data_ATAC_BCs-meta-data.csv` file, it does not have matching barcodes for the fragment file from the GEO. For example, "ACCACAACATACAGCT-RL2103_ga22_v3" is in the ATAC processed barcode file. But RL2103 is scRNA.... This line has rowname `RL1784#TTGCGGGCATTGCGAT-1` - RL1784 is also not valid sample. Can you fix this file? 

Another question is that I wanted to get the filtered barcodes you used. It seems that in the "GSM5138510_XXX_snATAC_singlecell.csv.gz" file, you put the column, "cell_id" where some cells have id but others have only "None". I think the cells with cell id are filtered barcodes. Is this correct?

Cheers,

**Comment by herrinca** [comment]
Apologies for not getting back in a timely mannor, we have just returned from our holiday break today.

Thank you for your kind words and for making us aware of this issue. I can not seem to find Processed_data_ATAC_BCs-meta-data.csv, can you point me to where you downloaded it from?

Thanks again,
Chuck

**Comment by joonan30** [comment]
Thanks Chuck,

`Processed_data_ATAC_BCs-meta-data.csv` is from Google Bucket from [here](https://console.cloud.google.com/storage/browser/neuro-dev/Processed_data;tab=objects?prefix=&forceOnObjectsSortingFiltering=false) 

Downloading the file by console converted the file name like above.. 

By the way, in the mean time, I dig your code and it seems pretty similar result as you got. 

Thanks

**Comment by herrinca** [comment]
Nice! Good to hear the code works outside of our hands. 

Oh ok. I should have pieced together that was the file, haha. 

I had a look back through that file and could only find RL2103_ga22_v3 listed in the "predictedCell" column, which is the closest matching snRNA-seq barcode to an ATAC barcode. Please let me know if I overlooked it listed as an ATAC barcode.

RL1784 is our 2yr ATAC sample, so it should be a valid ID. Are you using another source to cross-reference the ATAC sample IDs?

Best
