### ISSUE TITLE
Invalid labeling stage id of snRNA-seq barcode metadata file

### ISSUE THREAD

**Issue by koh2ng0** [ListerLab/pfc_development#4]
Dear Charles,

Thanks for offering the awesome dataset and code.

I have downloaded the metadata and processed snRNA-seq (.h5ad) through the google bucket [here](https://console.cloud.google.com/storage/browser/neuro-dev/Processed_data;tab=objects?prefix=&forceOnObjectsSortingFiltering=false).

By the way, when I checked the barcode metadata `Processed_data_RNA-all_BCs-meta-data.csv` for scRNA-seq data, the sample IDs and stage IDs were not matching. For example, the stage ID of 'RL1612' is 'Adult' in the metadata file. But, actually, RL1612 is 34 days old and in neonatal. Moreover, the processed snRNA-seq data (.h5ad) is too.

I think that the real developmental stages of samples and the stage ID labels are not concordant in the barcode metadata file and processed snRNA-seq data, is it correct that I checked?

**Comment by herrinca** [comment]
Hi Koh,

Many thanks for bringing this to our attention! You are correct they are not aligned in those files, I will get this fixed ASAP. I'll let you know once they have been corrected.  

Best,
Chuck

**Comment by koh2ng0** [comment]
Dear Chuck,

Thank you so much! I have one more ask about data for snATAC-seq processing. Is `2020-12-18_RAW_whole-tissue_post-restaged-GABA-clustering.RDS` used for `01_make_seRNA.R` of snATAC-seq code the same file as `RNA-all_full-counts-and-downsampled-CPM.h5ad` stored in the google bucket [here](https://console.cloud.google.com/storage/browser/_details/neuro-dev/Processed_data/RNA-all_full-counts-and-downsampled-CPM.h5ad;tab=live_object)?

Thanks.

**Comment by herrinca** [comment]
I will touch base with Saskia, who wrote that code and has since left the lab, and let you know.

**Comment by herrinca** [comment]
I was able to track down the snRNA developmental stage label bug. It was an unnecessary and foolish line of code that was added to reorder the stages for beatification purposes when plotted. I have rerun everything minus that line of code, and the corrected data is currently uploading to the same bucket. It should be finished uploading within the next 30-40min.

I will let you know about the ATAC data when I hear back from Saskia.

Thanks again for finding and reporting that misalignment, and please let us know if you find anything else!

**Comment by herrinca** [comment]
Saskia said it is correct to assume that 2020-12-18_RAW_whole-tissue_post-restaged-GABA-clustering.RDS used for 01_make_seRNA.R of snATAC-seq code is the same file as RNA-all_full-counts-and-downsampled-CPM.h5ad.

**Comment by herrinca** [comment]
Corrected data and added note to readme and publication website.
