### ISSUE TITLE
devDEGs not match

### ISSUE THREAD

**Issue by haotian-zhuang** [ListerLab/pfc_development#5]
Dear authors,

Thanks for providing the datasets. I have a question for the devDEGs part. I would like to first check if Supplemental Table 3 is the only way to extract the names of 14984 devDEGs?

After I manually extract the devDEGs from Table S3, the number is 14984 which is consistent to the paper. However, I found that one specific devDEGs (RP11-452D21.1) is not in the anndata object nor metadata for genes. Other 14983 devDEGs can be found in the anndata. Could you have a check?

Many thanks

**Comment by herrinca** [comment]
Hi,
The most direct and easiest way to extract the devDEG names is through Supplemental Table 3. The devDEGs for each trajectory can also be pulled from the results_file.txt in their respective glimma directories, which are accessible on [our website](http://brain.listerlab.org/). 

Thank you for bringing this to our attention. You are correct, RP11-452D21.1 was unknowingly filtered from the anndata object as it is expressed in very few cells in the L2/3 trajectory (see below). However, it is still included in both the single cell and bulk data used in our shiny-app plots, which can also be accessed from our website. 

Unless you would like access to RP11-452D21.1 ASAP, I will just make a note of it for the time being and correct it next time I have to run the data back through all the notebooks?

Thanks again!
Chuck 

![RP11-452D21 1](https://user-images.githubusercontent.com/8516872/216755172-357db829-5352-4fb1-a9d6-86a6d931a1e6.png)

**Comment by haotian-zhuang** [comment]
Hi Chuck,

Thanks so much for your timely reply! It's fine that you could correct it next time. I just want to reproduce some parts related to devDEGs, and it should fine if not including RP11-452D21.1.

Thanks,
Haotian

**Comment by herrinca** [comment]
I will update anndata object on next run throught to include RP11-452D21.1.
