### ISSUE TITLE
How to assign final annotation in scATAC-seq

### ISSUE THREAD

**Issue by koh2ng0** [ListerLab/pfc_development#6]
Dear Chuck,

Hi, I have a question about annotating with `scatac_clustering_annotation.xlsx` in `snATACseq/code/03_annotatino.R`.

I reproduced scATAC-seq dataset using your data and following your codes, but I encountered some problems with excluding clusters with low-quality cells and the final annotation using the excel file.

As I guess, the excel file used for the final annotation was written by researchers after QC processes. So I read the study method in the manuscript and the contents of the excel file, but I don't know exactly what criteria were used to exclude low-quality clusters.

There are conflicting criteria, in other words, some clusters have doublets over 20 but are not low quality, and some clusters don't have doublets over 20 but are low quality.

How can I exclude the clusters having low-quality cells?

**Comment by SaskiaFreytag** [comment]
Hi,

The removal of clusters worked on a more flexible qualitative review then just simply cut-off criteria. In fact from the paper: “ Further clusters that could not be confidently assigned to one cell type and probably constitute doublets or poor quality nuclei were identified. All these subclusters were labeled “Poor Quality” (constituting 4,281 nuclei) and removed from further analysis.”

I think the easiest way to replicate what we have done is to use the list of barcodes in the final filtered snATAC-seq dataset to subset your dataset. However you could also disagree with our assessment and decide on you own removal. Hope this helps.

Saskia

From: Koh ***@***.***>
Date: Monday, 6 February 2023 at 2:00 am
To: ListerLab/pfc_development ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ListerLab/pfc_development] How to assign final annotation in scATAC-seq (Issue #6)

Dear Chuck,

Hi, I have a question about annotating with scatac_clustering_annotation.xlsx in snATACseq/code/03_annotatino.R.

I reproduced scATAC-seq dataset using your data and following your codes, but I encountered some problems with excluding clusters with low-quality cells and the final annotation using the excel file.

As I guess, the excel file used for the final annotation was written by researchers after QC processes. So I read the study method in the manuscript and the contents of the excel file, but I don't know exactly what criteria were used to exclude low-quality clusters.

There are conflicting criteria, in other words, some clusters have doublets over 20 but are not low quality, and some clusters don't have doublets over 20 but are low quality.

How can I exclude the clusters having low-quality cells?

**Comment by herrinca** [comment]
I am going to close this for the time being. @koh2ng0 Please reopen if you have anymore questions or comments. 

Best,
Chuck
