### ISSUE TITLE
full-raw count matrix

### ISSUE THREAD

**Issue by haotian-zhuang** [ListerLab/pfc_development#7]
Hi Chuck,

I noticed that "the default count matrix in the RNA anndata objects are the full-raw counts" from the website, but the dimension of the default matrix is 154748*26747, which is same to the dimension of the downsampled CPM counts. So, I would like to check if the default count matrix is produced after or before the downsampling step?

I download the data from this link. "https://storage.googleapis.com/neuro-dev/Processed_data/RNA-all_full-counts-and-downsampled-CPM.h5ad".

Thanks,
Haotian

**Comment by herrinca** [comment]
Hi Haotain, 

In the default full count matrix I have removed barcodes with fewer than 1,000 UMIs due to poor quality. The UMI counts have not been changed. Within my notebooks, this was done within the same function as downsampling the counts, which may have caused confusion.

Best,
Chuck

**Comment by haotian-zhuang** [comment]
Hi Chuck,

Thanks, I see. Just to clarify, in your notebook, the genes was filtered from 28954 to 26747 (by min_cells = 5) after downsampling. So, if I downsample the default count matrix which contains 26747 genes, the result might not be exactly consistent to the downsampled CPM counts.

Thanks,
Haotian

**Comment by herrinca** [comment]
That is correct. If you were to downsample the 26,747 genes, full count matrix it would not significantly change the results, but it would not be identical to the supplied downsampled CPM counts.

**Comment by haotian-zhuang** [comment]
Thanks Chuck. This reminds me the question of missing devDEG "RP11-452D21.1" in the default full count matrix. It might be filtered from 29030 genes to 26747 genes step, while the devDEGs are detected from the "real" raw count including 29030 genes.

**Comment by herrinca** [comment]
I believe you are correct. My guess is that is where it was filtered.....and yes the devDEGs were called on pseudo bulked by batch full counts.

**Comment by haotian-zhuang** [comment]
Thank you Chuck! Is there any place I can find the pseudo-bulked trajectory data in your website, or I have to process from the full count matrix?

**Comment by herrinca** [comment]
Yeah, you can find the logTMM bulk data for each trajectory in their glimma interactive directories. For the example in the [L2/3_CUX2 glimma directory](http://brain.listerlab.org/assets/major_trajectories/glimma_dev-traj_major-clust_L2-3_CUX2/) the logTMM_cts.csv is the scaled and normalized bulked by batch data used to call devDEGs in the paper. Each trajectory has their own logTMM_cts.csv.

**Comment by haotian-zhuang** [comment]
Thank you Chuck! Your answer is very helpful.
