### ISSUE TITLE
scATAC-seq cluster annotation

### ISSUE THREAD

**Issue by koh2ng0** [ListerLab/pfc_development#9]
Hi, Chuck

I have a question about the process of annotating clusters in the scATAC-seq data. When annotating the scATAC-seq clusters, you integrated it with the scRNA-seq and calculated the confusion matrix of the "**predicatedGroup**". And then you confirmed that the cluster with the highest value was added as the "Cluster_sub". However, you didn't label it right away and added an annotation using a separate table `scatac_clustering_annotation.xlsx`. Can you tell me why you proceeded like that? In ArchR, 

Thanks,

**Comment by SaskiaFreytag** [comment]
Hi,

Labelling is never quite as easy as simply taking the most predicted annotation label in a cluster for the true label. Additionally to looking at this, we also looked at gene scores of known marker genes to make our final determination. I know that this might not be super satisfying but I don’t think labelling is a straightforward problem.

Cheers,

Saskia

From: Koh ***@***.***>
Date: Monday, 27 March 2023 at 12:50 am
To: ListerLab/pfc_development ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ListerLab/pfc_development] scATAC-seq cluster annotation (Issue #9)

Hi, Chuck

I have a question about the process of annotating clusters in the scATAC-seq data. When annotating the scATAC-seq clusters, you integrated it with the scRNA-seq and calculated the confusion matrix of the "predicatedGroup". And then you confirmed that the cluster with the highest value was added as the "Cluster_sub". However, you didn't label it right away and added an annotation using a separate table scatac_clustering_annotation.xlsx. Can you tell me why you proceeded like that? In ArchR,

Thanks,

**Comment by koh2ng0** [comment]
Thank you for your kind reply! I agree that labeling for clusters is not as easy as I think.
I wonder if the known marker gene used is the same as the one in the method of the manuscript.

Thanks,

**Comment by SaskiaFreytag** [comment]
Yes that is correct.

From: Koh ***@***.***>
Date: Monday, 27 March 2023 at 12:45 pm
To: ListerLab/pfc_development ***@***.***>
Cc: Saskia Freytag ***@***.***>, Assign ***@***.***>
Subject: Re: [ListerLab/pfc_development] scATAC-seq cluster annotation (Issue #9)

Thank you for your kind reply! I agree that labeling for clusters is not as easy as I think.
I wonder if the known marker gene used is the same as the one in the method of the manuscript.

Thanks,
